# Generated by Django 3.0.3 on 2020-03-06 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Articl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=255)),
                ('comment_count', models.IntegerField(default=0)),
                ('artcate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xl_app.Artcate')),
            ],
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='标签名称')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xl_app.Cate', verbose_name='所属博客')),
            ],
        ),
        migrations.AddField(
            model_name='cate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xl_app.UserInfo'),
        ),
        migrations.CreateModel(
            name='Article2Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xl_app.Articl', verbose_name='文章')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xl_app.Tag', verbose_name='标签')),
            ],
            options={
                'unique_together': {('article', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='articl',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xl_app.Cate'),
        ),
        migrations.AddField(
            model_name='articl',
            name='tags',
            field=models.ManyToManyField(through='xl_app.Article2Tag', to='xl_app.Tag'),
        ),
        migrations.AddField(
            model_name='artcate',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xl_app.Cate', verbose_name='所属博客'),
        ),
    ]
