# Generated by Django 3.0.3 on 2020-03-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xl_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
    ]
