# Generated by Django 3.0.3 on 2020-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xl_app', '0002_remove_userinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='articl',
            name='tags',
        ),
        migrations.AddField(
            model_name='articl',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, '分类阅读'), (2, '公开课'), (3, '每日精选'), (4, '提升自我'), (4, '技术区'), (4, '灌水区'), (4, '创作区')], default=1),
        ),
        migrations.AlterField(
            model_name='articl',
            name='comment_count',
            field=models.IntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='Article2Tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
